services:
  git:
    image: codeberg.org/forgejo/forgejo:13.0.3
    container_name: git_ui
    mem_limit: 1g
    cpus: "2.0"
    restart: always
    depends_on:
      - git_db
    ports:
      - "8000:3000"
      - "22:22"
    environment:
      USER_UID: 1000
      USER_GID: 1000
      DB_TYPE: postgres
      DB_HOST: git_db
      DB_NAME: git
      DB_USER: git
      DB_PASSWD: ${DB_PASSWD}
      APP_NAME: git
      FORGEJO__APP__DEFAULT_LANG: en-US
    volumes:
      - git_data:/data

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  git_db:
    image: postgres:18
    container_name: git_db
    mem_limit: 1g
    cpus: "2.0"
    restart: always
    environment:
      POSTGRES_USER: git
      POSTGRES_PASSWORD: ${DB_PASSWD}
      POSTGRES_DB: git
    volumes:
      - git_db_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U git"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  git_db_data:
  git_data:
